import type { Metadata } from "next";
import "./globals.css";

// NOTE: the default create-next-app template used next/font/google (Geist).
// This sandbox's network cannot reach fonts.googleapis.com/fonts.gstatic.com,
// which broke `npm run build` here. Task 32 (branding pass) replaces this
// placeholder entirely with the InVnity brand fonts (Bebas Neue / Montserrat)
// self-hosted via next/font/local, so no next/font/google usage remains
// anywhere in the finished app.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
